// List of representative IANA timezones, one per GMT offset, with GMT in parentheses
export const timezones = [
  { tz: "Pacific/Midway", label: "Pacific/Midway (GMT-11:00)" },
  { tz: "Pacific/Honolulu", label: "Pacific/Honolulu (GMT-10:00)" },
  { tz: "America/Anchorage", label: "America/Anchorage (GMT-09:00)" },
  { tz: "America/Los_Angeles", label: "America/Los_Angeles (GMT-08:00)" },
  { tz: "America/Denver", label: "America/Denver (GMT-07:00)" },
  { tz: "America/Chicago", label: "America/Chicago (GMT-06:00)" },
  { tz: "America/New_York", label: "America/New_York (GMT-05:00)" },
  { tz: "America/Caracas", label: "America/Caracas (GMT-04:00)" },
  { tz: "America/Sao_Paulo", label: "America/Sao_Paulo (GMT-03:00)" },
  { tz: "Atlantic/South_Georgia", label: "Atlantic/South_Georgia (GMT-02:00)" },
  { tz: "Atlantic/Azores", label: "Atlantic/Azores (GMT-01:00)" },
  { tz: "Europe/London", label: "Europe/London (GMT+00:00)" },
  { tz: "Europe/Berlin", label: "Europe/Berlin (GMT+01:00)" },
  { tz: "Africa/Cairo", label: "Africa/Cairo (GMT+02:00)" },
  { tz: "Europe/Moscow", label: "Europe/Moscow (GMT+03:00)" },
  { tz: "Asia/Dubai", label: "Asia/Dubai (GMT+04:00)" },
  { tz: "Asia/Karachi", label: "Asia/Karachi (GMT+05:00)" },
  { tz: "Asia/Kathmandu", label: "Asia/Kathmandu (GMT+05:45)" },
  { tz: "Asia/Kolkata", label: "Asia/Kolkata (GMT+05:30)" },
  { tz: "Asia/Almaty", label: "Asia/Almaty (GMT+06:00)" },
  { tz: "Asia/Yangon", label: "Asia/Yangon (GMT+06:30)" },
  { tz: "Asia/Bangkok", label: "Asia/Bangkok (GMT+07:00)" },
  { tz: "Asia/Shanghai", label: "Asia/Shanghai (GMT+08:00)" },
  { tz: "Asia/Tokyo", label: "Asia/Tokyo (GMT+09:00)" },
  { tz: "Australia/Adelaide", label: "Australia/Adelaide (GMT+09:30)" },
  { tz: "Australia/Sydney", label: "Australia/Sydney (GMT+10:00)" },
  { tz: "Pacific/Guadalcanal", label: "Pacific/Guadalcanal (GMT+11:00)" },
  { tz: "Pacific/Auckland", label: "Pacific/Auckland (GMT+12:00)" },
  { tz: "Pacific/Chatham", label: "Pacific/Chatham (GMT+12:45)" },
];
